language: node_js
node_js:
  - "stable"
matrix:
  fast_finish: true
  include:
    - env: ECMAScript
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/templates/ECMAScript
        - npm install
      script:
        - npm test
        - npm run lint
        - npm run build
    - env: TypeScript
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/templates/TypeScript
        - npm install
      script:
        - npm test
        - npm run lint
        - npm run build
